### ISSUE TITLE
fix version info

### ISSUE THREAD

**Issue by VladimirAlexiev** [Interoperable-data/ERA-Ontology-3.1.0#49]
```ttl
  owl:versionInfo "v3.1.0"@en ;
  owl:priorVersion "https://git.fpfis.eu/datateam/ERA/era-vocabulary/-/releases/v3.0.0"@en ;
  owl:versionURI "https://git.fpfis.eu/datateam/ERA/era-vocabulary/-/releases/v3.1.0"@en .
```
There are a couple of problems:
- "v3.1.0" is not an English phrase, so please remove the lang tag
- https://git.fpfis.eu is dead (https://github.com/Interoperable-data/ERA-Ontology-3.1.0/issues/48), and it's not the master location of the ontology anyway. 
- Please decide whether you'll use https://github.com/Interoperable-data/ERA_vocabulary or maybe https://github.com/Interoperable-data/ERA-Ontology as the master location for the ontology
- There are no Releases in https://github.com/Interoperable-data/ERA_vocabulary but I think you should start recording releases, then you can use a "releases" URL in `priorVersion, versionURI`
- Last but not least, replace these with real URLs rather than langStrings. Eg:
```ttl
    owl:versionURI <https://github.com/Interoperable-data/ERA_vocabulary/release/v3.1.0>
```

**Comment by Interoperable-data** [comment]
Fixed, thanks!

**Comment by VladimirAlexiev** [comment]
@Interoperable-data This is not quite fixed:
```
 owl:priorVersion "https://github.com/Interoperable-data/ERA_vocabulary/releases/v3.0.0"^^xsd:anyURI ; # should be URL not litral
 owl:versionInfo "v3.1.0"@en ; # shoulnd't be `@en`
 owl:versionURI <https://github.com/Interoperable-data/ERA_vocabulary/releases/releases/v3.1.0> ; # broken link: doubled word
```
It's strange that https://github.com/Interoperable-data/ERA_vocabulary/releases/v3.0.0 works,
but  https://github.com/Interoperable-data/ERA_vocabulary/releases/v3.1.0 doesn't work.

This works: https://github.com/Interoperable-data/ERA_vocabulary/releases/tag/v3.0.1 (with `tag/`).
